
project_id = "kgizusgqexmlfcqfjopk"

[functions.get-all-users]
verify_jwt = true

[functions.get-users-admin]
verify_jwt = false

[functions.cleanup-batch-jobs]
verify_jwt = false

[functions.calculate-due-dates]
verify_jwt = true
