
# This is a config file for the Supabase CLI
# It allows to configure project settings

# The project ID of the Supabase project
project_id = "kgizusgqexmlfcqfjopk"

[api]
# Port on which the API will be served
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.cors]
enabled = true
origin = "*"

[db]
# Port on which the database will be served
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.io"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "https://kgizusgqexmlfcqfjopk.lovable.dev"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_account_linking = true

[auth.email]
enabled = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[storage]
enabled = true
file_size_limit = "50MiB"

[functions]
enabled = true
serve_port = 54325
[functions.get-all-users]
verify_jwt = true
[functions.create-user]
verify_jwt = true
