
project_id = "kgizusgqexmlfcqfjopk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.get-all-users]
verify_jwt = true

[functions.get-users-admin]
verify_jwt = false

[functions.cleanup-batch-jobs]
verify_jwt = false

[functions.calculate-due-dates]
verify_jwt = true

[functions.nightly-schedule-update]
verify_jwt = false

[analytics]
enabled = false
