project_id = "kgizusgqexmlfcqfjopk"

[functions.proof-approval-flow]
verify_jwt = true

[functions.simple-scheduler]
verify_jwt = false

[functions.get-all-users]
verify_jwt = true

[functions.get-users-admin]
verify_jwt = false

[functions.cleanup-batch-jobs]
verify_jwt = false

[functions.calculate-due-dates]
verify_jwt = true

# Public functions used by scheduling engine (invoked by DB trigger and cron)
[functions.schedule-on-approval]
verify_jwt = false

[functions.recalc-tentative-due-dates]
verify_jwt = false

[functions.manual-reschedule-stage]
verify_jwt = true

[functions.auto-schedule-approved]
verify_jwt = false

# NEW PARALLEL CAPACITY SCHEDULER: Fixes "Monday to Friday" gaps
[functions.parallel-auto-scheduler]
verify_jwt = false
