
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgizusgqexmlfcqfjopk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnaXp1c2dxZXhtbGZjcWZqb3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTQwNzAsImV4cCI6MjA2MDEzMDA3MH0.NA2wRme-L8Z15my7n8u-BCQtO4Nw2opfsX0KSLYcs-I";

// Enhanced preview mode detection with multiple indicators
export const isLovablePreview = 
  typeof window !== 'undefined' && 
  (window.location.hostname.includes('lovable.dev') || 
   window.location.hostname.includes('gpteng.co') ||
   window.location.hostname === 'localhost' ||
   window.location.hostname === '127.0.0.1');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disabled for security
    flowType: 'implicit' // Changed from 'pkce' to 'implicit' flow
  },
  global: {
    // Always use HTTP fetch for all operations to avoid WebSocket issues
    fetch: function(url, options) {
      // Add debugging information
      console.log('Supabase client making request to:', url);
      
      // Create a fetch request with timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout
      
      return fetch(url, { 
        ...options, 
        signal: controller.signal 
      }).then(response => {
        clearTimeout(timeoutId);
        return response;
      }).catch(error => {
        clearTimeout(timeoutId);
        console.error('Fetch error in supabase client:', error);
        throw error;
      });
    }
  },
  realtime: {
    // Disable realtime features in preview mode to prevent WebSocket connection issues
    params: {
      eventsPerSecond: isLovablePreview ? 0 : 10
    }
  }
});

// Create a dedicated client for admin operations and edge function calls
// This client ensures HTTP/REST is used and no WebSocket connections are attempted
export const adminClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'implicit'
  },
  realtime: {
    // Disable realtime connections completely
    params: {
      eventsPerSecond: 0
    }
  },
  global: {
    // Force HTTP/HTTPS fetch for all operations with timeout
    fetch: function(url, options) {
      // Add debugging information
      console.log('Admin client making request to:', url);
      
      // Create a fetch request with timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout
      
      return fetch(url, { 
        ...options, 
        signal: controller.signal 
      }).then(response => {
        clearTimeout(timeoutId);
        return response;
      }).catch(error => {
        clearTimeout(timeoutId);
        console.error('Fetch error in admin client:', error);
        throw error;
      });
    }
  }
});
