
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgizusgqexmlfcqfjopk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnaXp1c2dxZXhtbGZjcWZqb3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTQwNzAsImV4cCI6MjA2MDEzMDA3MH0.NA2wRme-L8Z15my7n8u-BCQtO4Nw2opfsX0KSLYcs-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    // Disable WebSockets globally to ensure HTTP is used for all operations
    fetch: function(url, options) {
      return fetch(url, options);
    }
  },
  realtime: {
    // Disable realtime features to prevent WebSocket connection issues
    params: {
      eventsPerSecond: 0
    }
  }
});

// Create a dedicated client for admin operations and edge function calls
// This client ensures HTTP/REST is used and no WebSocket connections are attempted
export const adminClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce'
  },
  realtime: {
    // Disable realtime connections by setting low parameters
    params: {
      eventsPerSecond: 0
    }
  },
  global: {
    // Force HTTP/HTTPS fetch for all operations
    fetch: function(url, options) {
      return fetch(url, options);
    }
  }
});
